(function() {var implementors = {};
implementors["wayland_client"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"wayland_client/struct.EventQueue.html\" title=\"struct wayland_client::EventQueue\">EventQueue</a>","impl&lt;H:&nbsp;EnvHandlerInner&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"wayland_client/struct.EnvHandler.html\" title=\"struct wayland_client::EnvHandler\">EnvHandler</a>&lt;H&gt;","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"wayland_client/cursor/struct.CursorImageBuffer.html\" title=\"struct wayland_client::cursor::CursorImageBuffer\">CursorImageBuffer</a>&lt;'a&gt;",];
implementors["wayland_server"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"wayland_server/struct.EventLoop.html\" title=\"struct wayland_server::EventLoop\">EventLoop</a>",];
implementors["wayland_sys"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"wayland_sys/client/struct.WAYLAND_CLIENT_OPTION.html\" title=\"struct wayland_sys::client::WAYLAND_CLIENT_OPTION\">WAYLAND_CLIENT_OPTION</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"wayland_sys/client/struct.WAYLAND_CLIENT_HANDLE.html\" title=\"struct wayland_sys::client::WAYLAND_CLIENT_HANDLE\">WAYLAND_CLIENT_HANDLE</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"wayland_sys/server/struct.WAYLAND_SERVER_OPTION.html\" title=\"struct wayland_sys::server::WAYLAND_SERVER_OPTION\">WAYLAND_SERVER_OPTION</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"wayland_sys/server/struct.WAYLAND_SERVER_HANDLE.html\" title=\"struct wayland_sys::server::WAYLAND_SERVER_HANDLE\">WAYLAND_SERVER_HANDLE</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"wayland_sys/egl/struct.WAYLAND_EGL_OPTION.html\" title=\"struct wayland_sys::egl::WAYLAND_EGL_OPTION\">WAYLAND_EGL_OPTION</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"wayland_sys/egl/struct.WAYLAND_EGL_HANDLE.html\" title=\"struct wayland_sys::egl::WAYLAND_EGL_HANDLE\">WAYLAND_EGL_HANDLE</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"wayland_sys/cursor/struct.WAYLAND_CURSOR_OPTION.html\" title=\"struct wayland_sys::cursor::WAYLAND_CURSOR_OPTION\">WAYLAND_CURSOR_OPTION</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"wayland_sys/cursor/struct.WAYLAND_CURSOR_HANDLE.html\" title=\"struct wayland_sys::cursor::WAYLAND_CURSOR_HANDLE\">WAYLAND_CURSOR_HANDLE</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
